// Code generated by protoc-gen-go. DO NOT EDIT.
// source: depend.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DependRequest struct {
	DependName           string   `protobuf:"bytes,1,opt,name=dependName,proto3" json:"dependName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependRequest) Reset()         { *m = DependRequest{} }
func (m *DependRequest) String() string { return proto.CompactTextString(m) }
func (*DependRequest) ProtoMessage()    {}
func (*DependRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_depend_478bf20a4df9c9c0, []int{0}
}
func (m *DependRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependRequest.Unmarshal(m, b)
}
func (m *DependRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependRequest.Marshal(b, m, deterministic)
}
func (dst *DependRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependRequest.Merge(dst, src)
}
func (m *DependRequest) XXX_Size() int {
	return xxx_messageInfo_DependRequest.Size(m)
}
func (m *DependRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DependRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DependRequest proto.InternalMessageInfo

func (m *DependRequest) GetDependName() string {
	if m != nil {
		return m.DependName
	}
	return ""
}

type DependResponse struct {
	DependMessage        string   `protobuf:"bytes,1,opt,name=dependMessage,proto3" json:"dependMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependResponse) Reset()         { *m = DependResponse{} }
func (m *DependResponse) String() string { return proto.CompactTextString(m) }
func (*DependResponse) ProtoMessage()    {}
func (*DependResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_depend_478bf20a4df9c9c0, []int{1}
}
func (m *DependResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependResponse.Unmarshal(m, b)
}
func (m *DependResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependResponse.Marshal(b, m, deterministic)
}
func (dst *DependResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependResponse.Merge(dst, src)
}
func (m *DependResponse) XXX_Size() int {
	return xxx_messageInfo_DependResponse.Size(m)
}
func (m *DependResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DependResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DependResponse proto.InternalMessageInfo

func (m *DependResponse) GetDependMessage() string {
	if m != nil {
		return m.DependMessage
	}
	return ""
}

type Bot struct {
	Run                  string   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Say                  []byte   `protobuf:"bytes,2,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bot) Reset()         { *m = Bot{} }
func (m *Bot) String() string { return proto.CompactTextString(m) }
func (*Bot) ProtoMessage()    {}
func (*Bot) Descriptor() ([]byte, []int) {
	return fileDescriptor_depend_478bf20a4df9c9c0, []int{2}
}
func (m *Bot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bot.Unmarshal(m, b)
}
func (m *Bot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bot.Marshal(b, m, deterministic)
}
func (dst *Bot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bot.Merge(dst, src)
}
func (m *Bot) XXX_Size() int {
	return xxx_messageInfo_Bot.Size(m)
}
func (m *Bot) XXX_DiscardUnknown() {
	xxx_messageInfo_Bot.DiscardUnknown(m)
}

var xxx_messageInfo_Bot proto.InternalMessageInfo

func (m *Bot) GetRun() string {
	if m != nil {
		return m.Run
	}
	return ""
}

func (m *Bot) GetSay() []byte {
	if m != nil {
		return m.Say
	}
	return nil
}

func init() {
	proto.RegisterType((*DependRequest)(nil), "proto.DependRequest")
	proto.RegisterType((*DependResponse)(nil), "proto.DependResponse")
	proto.RegisterType((*Bot)(nil), "proto.Bot")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DependServerClient is the client API for DependServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependServerClient interface {
	DependHello(ctx context.Context, in *DependRequest, opts ...grpc.CallOption) (*DependResponse, error)
}

type dependServerClient struct {
	cc *grpc.ClientConn
}

func NewDependServerClient(cc *grpc.ClientConn) DependServerClient {
	return &dependServerClient{cc}
}

func (c *dependServerClient) DependHello(ctx context.Context, in *DependRequest, opts ...grpc.CallOption) (*DependResponse, error) {
	out := new(DependResponse)
	err := c.cc.Invoke(ctx, "/proto.DependServer/DependHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependServerServer is the server API for DependServer service.
type DependServerServer interface {
	DependHello(context.Context, *DependRequest) (*DependResponse, error)
}

func RegisterDependServerServer(s *grpc.Server, srv DependServerServer) {
	s.RegisterService(&_DependServer_serviceDesc, srv)
}

func _DependServer_DependHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependServerServer).DependHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DependServer/DependHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependServerServer).DependHello(ctx, req.(*DependRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DependServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DependServer",
	HandlerType: (*DependServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DependHello",
			Handler:    _DependServer_DependHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "depend.proto",
}

func init() { proto.RegisterFile("depend.proto", fileDescriptor_depend_478bf20a4df9c9c0) }

var fileDescriptor_depend_478bf20a4df9c9c0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0x48,
	0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xfa, 0x5c, 0xbc,
	0x2e, 0x60, 0xe1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x39, 0x2e, 0x2e, 0x88, 0x3a,
	0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x25, 0x33, 0x2e,
	0x3e, 0x98, 0x86, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x15, 0x2e, 0x5e, 0x88, 0xbc, 0x6f,
	0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x13, 0xaa, 0xa0, 0x92, 0x26, 0x17, 0xb3, 0x53, 0x7e, 0x89,
	0x90, 0x00, 0x17, 0x73, 0x51, 0x69, 0x1e, 0x54, 0x09, 0x88, 0x09, 0x12, 0x29, 0x4e, 0xac, 0x94,
	0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0x31, 0x8d, 0x7c, 0xb8, 0x78, 0x20, 0x56, 0x04, 0xa7,
	0x16, 0x95, 0xa5, 0x16, 0x09, 0xd9, 0x70, 0x71, 0x43, 0xf8, 0x1e, 0xa9, 0x39, 0x39, 0xf9, 0x42,
	0x22, 0x10, 0x1f, 0xe8, 0xa1, 0xb8, 0x5b, 0x4a, 0x14, 0x4d, 0x14, 0xe2, 0x38, 0x25, 0x86, 0x24,
	0x36, 0xb0, 0xb8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x64, 0xc8, 0x41, 0xff, 0x00, 0x00,
	0x00,
}
