// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/depend.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DependRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DependName string `protobuf:"bytes,1,opt,name=dependName,proto3" json:"dependName,omitempty"`
}

func (x *DependRequest) Reset() {
	*x = DependRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_depend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependRequest) ProtoMessage() {}

func (x *DependRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependRequest.ProtoReflect.Descriptor instead.
func (*DependRequest) Descriptor() ([]byte, []int) {
	return file_proto_depend_proto_rawDescGZIP(), []int{0}
}

func (x *DependRequest) GetDependName() string {
	if x != nil {
		return x.DependName
	}
	return ""
}

type DependResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DependMessage string `protobuf:"bytes,1,opt,name=dependMessage,proto3" json:"dependMessage,omitempty"`
}

func (x *DependResponse) Reset() {
	*x = DependResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_depend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DependResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependResponse) ProtoMessage() {}

func (x *DependResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependResponse.ProtoReflect.Descriptor instead.
func (*DependResponse) Descriptor() ([]byte, []int) {
	return file_proto_depend_proto_rawDescGZIP(), []int{1}
}

func (x *DependResponse) GetDependMessage() string {
	if x != nil {
		return x.DependMessage
	}
	return ""
}

type Bot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Run string `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Say []byte `protobuf:"bytes,2,opt,name=say,proto3" json:"say,omitempty"`
}

func (x *Bot) Reset() {
	*x = Bot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_depend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_proto_depend_proto_rawDescGZIP(), []int{2}
}

func (x *Bot) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

func (x *Bot) GetSay() []byte {
	if x != nil {
		return x.Say
	}
	return nil
}

var File_proto_depend_proto protoreflect.FileDescriptor

var file_proto_depend_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x0d, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0e,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x03, 0x42, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x61, 0x79, 0x32,
	0x4c, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x3c, 0x0a, 0x0b, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_depend_proto_rawDescOnce sync.Once
	file_proto_depend_proto_rawDescData = file_proto_depend_proto_rawDesc
)

func file_proto_depend_proto_rawDescGZIP() []byte {
	file_proto_depend_proto_rawDescOnce.Do(func() {
		file_proto_depend_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_depend_proto_rawDescData)
	})
	return file_proto_depend_proto_rawDescData
}

var file_proto_depend_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_depend_proto_goTypes = []interface{}{
	(*DependRequest)(nil),  // 0: proto.DependRequest
	(*DependResponse)(nil), // 1: proto.DependResponse
	(*Bot)(nil),            // 2: proto.Bot
}
var file_proto_depend_proto_depIdxs = []int32{
	0, // 0: proto.DependServer.DependHello:input_type -> proto.DependRequest
	1, // 1: proto.DependServer.DependHello:output_type -> proto.DependResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_depend_proto_init() }
func file_proto_depend_proto_init() {
	if File_proto_depend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_depend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_depend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DependResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_depend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_depend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_depend_proto_goTypes,
		DependencyIndexes: file_proto_depend_proto_depIdxs,
		MessageInfos:      file_proto_depend_proto_msgTypes,
	}.Build()
	File_proto_depend_proto = out.File
	file_proto_depend_proto_rawDesc = nil
	file_proto_depend_proto_goTypes = nil
	file_proto_depend_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DependServerClient is the client API for DependServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependServerClient interface {
	DependHello(ctx context.Context, in *DependRequest, opts ...grpc.CallOption) (*DependResponse, error)
}

type dependServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDependServerClient(cc grpc.ClientConnInterface) DependServerClient {
	return &dependServerClient{cc}
}

func (c *dependServerClient) DependHello(ctx context.Context, in *DependRequest, opts ...grpc.CallOption) (*DependResponse, error) {
	out := new(DependResponse)
	err := c.cc.Invoke(ctx, "/proto.DependServer/DependHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependServerServer is the server API for DependServer service.
type DependServerServer interface {
	DependHello(context.Context, *DependRequest) (*DependResponse, error)
}

// UnimplementedDependServerServer can be embedded to have forward compatible implementations.
type UnimplementedDependServerServer struct {
}

func (*UnimplementedDependServerServer) DependHello(context.Context, *DependRequest) (*DependResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DependHello not implemented")
}

func RegisterDependServerServer(s *grpc.Server, srv DependServerServer) {
	s.RegisterService(&_DependServer_serviceDesc, srv)
}

func _DependServer_DependHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DependRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependServerServer).DependHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DependServer/DependHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependServerServer).DependHello(ctx, req.(*DependRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DependServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DependServer",
	HandlerType: (*DependServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DependHello",
			Handler:    _DependServer_DependHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/depend.proto",
}
