// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_574d74f916b8b8cb, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Bot                  *Bot     `protobuf:"bytes,2,opt,name=bot,proto3" json:"bot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_574d74f916b8b8cb, []int{1}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloResponse) GetBot() *Bot {
	if m != nil {
		return m.Bot
	}
	return nil
}

type HelloStreamRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloStreamRequest) Reset()         { *m = HelloStreamRequest{} }
func (m *HelloStreamRequest) String() string { return proto.CompactTextString(m) }
func (*HelloStreamRequest) ProtoMessage()    {}
func (*HelloStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_574d74f916b8b8cb, []int{2}
}
func (m *HelloStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloStreamRequest.Unmarshal(m, b)
}
func (m *HelloStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloStreamRequest.Marshal(b, m, deterministic)
}
func (dst *HelloStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloStreamRequest.Merge(dst, src)
}
func (m *HelloStreamRequest) XXX_Size() int {
	return xxx_messageInfo_HelloStreamRequest.Size(m)
}
func (m *HelloStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloStreamRequest proto.InternalMessageInfo

func (m *HelloStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloStreamResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloStreamResponse) Reset()         { *m = HelloStreamResponse{} }
func (m *HelloStreamResponse) String() string { return proto.CompactTextString(m) }
func (*HelloStreamResponse) ProtoMessage()    {}
func (*HelloStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_helloworld_574d74f916b8b8cb, []int{3}
}
func (m *HelloStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloStreamResponse.Unmarshal(m, b)
}
func (m *HelloStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloStreamResponse.Marshal(b, m, deterministic)
}
func (dst *HelloStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloStreamResponse.Merge(dst, src)
}
func (m *HelloStreamResponse) XXX_Size() int {
	return xxx_messageInfo_HelloStreamResponse.Size(m)
}
func (m *HelloStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloStreamResponse proto.InternalMessageInfo

func (m *HelloStreamResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "proto.HelloResponse")
	proto.RegisterType((*HelloStreamRequest)(nil), "proto.HelloStreamRequest")
	proto.RegisterType((*HelloStreamResponse)(nil), "proto.HelloStreamResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// 双向流
	DoubleStreamHello(ctx context.Context, opts ...grpc.CallOption) (HelloWorld_DoubleStreamHelloClient, error)
}

type helloWorldClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldClient(cc *grpc.ClientConn) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/proto.HelloWorld/hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloWorldClient) DoubleStreamHello(ctx context.Context, opts ...grpc.CallOption) (HelloWorld_DoubleStreamHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HelloWorld_serviceDesc.Streams[0], "/proto.HelloWorld/DoubleStreamHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloWorldDoubleStreamHelloClient{stream}
	return x, nil
}

type HelloWorld_DoubleStreamHelloClient interface {
	Send(*HelloStreamRequest) error
	Recv() (*HelloStreamResponse, error)
	grpc.ClientStream
}

type helloWorldDoubleStreamHelloClient struct {
	grpc.ClientStream
}

func (x *helloWorldDoubleStreamHelloClient) Send(m *HelloStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloWorldDoubleStreamHelloClient) Recv() (*HelloStreamResponse, error) {
	m := new(HelloStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	// 双向流
	DoubleStreamHello(HelloWorld_DoubleStreamHelloServer) error
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloWorld/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloWorld_DoubleStreamHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloWorldServer).DoubleStreamHello(&helloWorldDoubleStreamHelloServer{stream})
}

type HelloWorld_DoubleStreamHelloServer interface {
	Send(*HelloStreamResponse) error
	Recv() (*HelloStreamRequest, error)
	grpc.ServerStream
}

type helloWorldDoubleStreamHelloServer struct {
	grpc.ServerStream
}

func (x *helloWorldDoubleStreamHelloServer) Send(m *HelloStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloWorldDoubleStreamHelloServer) Recv() (*HelloStreamRequest, error) {
	m := new(HelloStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "hello",
			Handler:    _HelloWorld_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoubleStreamHello",
			Handler:       _HelloWorld_DoubleStreamHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_helloworld_574d74f916b8b8cb) }

var fileDescriptor_helloworld_574d74f916b8b8cb = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xb1, 0x4e, 0x80, 0x30,
	0x10, 0x86, 0xad, 0x8a, 0xc6, 0x13, 0x13, 0x3d, 0x1c, 0xb0, 0x71, 0x20, 0x9d, 0xea, 0x42, 0x0c,
	0xfa, 0x04, 0xc6, 0x44, 0x47, 0x83, 0x83, 0x33, 0x84, 0x8b, 0x0e, 0x85, 0x43, 0x5a, 0xe2, 0x8b,
	0xf8, 0xc0, 0x86, 0x52, 0x12, 0x48, 0x88, 0x53, 0xdb, 0xbb, 0x2f, 0xff, 0xd7, 0x1f, 0x2e, 0xbf,
	0xc8, 0x18, 0xfe, 0xe1, 0xc1, 0x34, 0x79, 0x3f, 0xb0, 0x63, 0x8c, 0xfc, 0x21, 0xe3, 0x86, 0x7a,
	0xea, 0xc2, 0x50, 0x29, 0x88, 0x5f, 0x27, 0xb0, 0xa4, 0xef, 0x91, 0xac, 0x43, 0x84, 0xe3, 0xae,
	0x6a, 0x29, 0x15, 0x99, 0xd0, 0x67, 0xa5, 0xbf, 0xab, 0x17, 0xb8, 0x08, 0x8c, 0xed, 0xb9, 0xb3,
	0x84, 0x29, 0x9c, 0xb6, 0x64, 0x6d, 0xf5, 0xb9, 0x70, 0xcb, 0x13, 0x6f, 0xe1, 0xa8, 0x66, 0x97,
	0x1e, 0x66, 0x42, 0x9f, 0x17, 0x30, 0x3b, 0xf2, 0x27, 0x76, 0xe5, 0x34, 0x56, 0x1a, 0xd0, 0x07,
	0xbd, 0xbb, 0x81, 0xaa, 0xf6, 0x3f, 0xe5, 0x1d, 0x24, 0x1b, 0x32, 0x88, 0x77, 0xd0, 0xe2, 0x57,
	0x00, 0x78, 0xf6, 0x63, 0xea, 0x8a, 0x8f, 0x10, 0xf9, 0xe6, 0x98, 0x04, 0xfb, 0xba, 0x9e, 0xbc,
	0xde, 0x0e, 0xe7, 0x58, 0x75, 0x80, 0x6f, 0x70, 0xf5, 0xcc, 0x63, 0x6d, 0x68, 0x16, 0xfa, 0x35,
	0xde, 0xac, 0xe1, 0xcd, 0x9f, 0xa5, 0xdc, 0x5b, 0x2d, 0x69, 0x5a, 0xdc, 0x8b, 0xfa, 0xc4, 0x03,
	0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x57, 0x65, 0x57, 0x88, 0x01, 0x00, 0x00,
}
